# Generated by Django 5.2.16 on 2026-07-27 09:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=600)),
                ('cuisine', models.CharField(blank=True, max_length=60)),
                ('address', models.CharField(max_length=180)),
                ('city', models.CharField(max_length=80)),
                ('postcode', models.CharField(db_index=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('banner_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_open', models.BooleanField(db_index=True, default=True)),
                ('delivery_enabled', models.BooleanField(default=False)),
                ('pickup_enabled', models.BooleanField(default=True)),
                ('onsite_enabled', models.BooleanField(default=False)),
                ('minimum_order', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='restaurants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['is_active', 'is_open', 'name'], name='restaurants_is_acti_022f48_idx'), models.Index(fields=['postcode', 'is_active'], name='restaurants_postcod_718718_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('minimum_order__gte', 0)), name='restaurant_minimum_order_non_negative'), models.CheckConstraint(condition=models.Q(('delivery_fee__gte', 0)), name='restaurant_delivery_fee_non_negative')],
            },
        ),
    ]
