# Generated by Django 5.2.16 on 2026-07-27 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('converted', 'Converti'), ('abandoned', 'Abandonné')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carts', to='restaurants.restaurant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('fingerprint', models.CharField(max_length=64)),
                ('product_name', models.CharField(max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carts.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=80)),
                ('option_name', models.CharField(max_length=80)),
                ('price_delta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='carts.cartitem')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.productoption')),
            ],
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['status', 'updated_at'], name='carts_cart_status_072be2_idx'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), models.Q(('session_key', ''), _negated=True), _connector='OR'), name='cart_has_user_or_session'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active'), ('user__isnull', False)), fields=('user',), name='one_active_cart_per_user'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active'), models.Q(('session_key', ''), _negated=True)), fields=('session_key',), name='one_active_cart_per_session'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='cart_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__lte', 99)), name='cart_item_quantity_max_99'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='cart_item_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'fingerprint'), name='unique_configured_product_per_cart'),
        ),
        migrations.AddConstraint(
            model_name='cartitemoption',
            constraint=models.UniqueConstraint(fields=('item', 'option'), name='unique_option_per_cart_item'),
        ),
        migrations.AddConstraint(
            model_name='cartitemoption',
            constraint=models.CheckConstraint(condition=models.Q(('price_delta__gte', 0)), name='cart_option_price_non_negative'),
        ),
    ]
