"use client";
import { Bell, ChevronRight, ClipboardList, LayoutDashboard, Menu, PackageCheck, RefreshCw, TrendingUp, UserRound, X } from "lucide-react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useMe } from "@/features/api-hooks";
import { money } from "@/lib/api-client";
const demo=[{id:"KG-8421",status:"pending",customer:"Sarah Martin",address:"12 rue du Faubourg, Paris",time:"12:42",total:"32.50",items:"2 × Burger maison, 1 × Frites cheddar"},{id:"KG-8419",status:"in_preparation",customer:"Yanis Benali",address:"8 avenue de la République, Paris",time:"12:35",total:"24.00",items:"1 × Tacos double, 1 × Cola"},{id:"KG-8417",status:"ready",customer:"Emma Dupont",address:"3 impasse des Lilas, Paris",time:"12:21",total:"41.00",items:"2 × Assiette entrecôte, 1 × Frites"}];
const labels:Record<string,string>={pending:"Nouvelle",confirmed:"Confirmée",in_preparation:"En préparation",ready:"Prête",completed:"Terminée",cancelled:"Abandonnée"};
export function RestaurateurShell({view="dashboard"}:{view?:"dashboard"|"history"|"stats"}){const path=usePathname(),me=useMe(),[open,setOpen]=React.useState(false);const nav=[{href:"/restaurateur",label:"Réception",Icon:LayoutDashboard},{href:"/restaurateur/historique",label:"Historique",Icon:ClipboardList},{href:"/restaurateur/statistiques",label:"Statistiques",Icon:TrendingUp}];const orders=demo;const stats={orders_today:18,orders_month:426,completed:398,abandoned:28,top_products:[{name:'Burger maison',quantity:142},{name:'Tacos double',quantity:119},{name:'Frites cheddar',quantity:96}]};return <div className="resto-app"><aside className={`resto-sidebar ${open?'resto-sidebar--open':''}`}><div className="resto-sidebar__brand"><Link className="brand" href="/"><span className="brand__mark">K</span><span>KomandGo</span></Link><button className="icon-button resto-close" onClick={()=>setOpen(false)} aria-label="Fermer le menu"><X/></button></div><div className="resto-profile"><span className="resto-avatar">{(me.data?.first_name||'R').slice(0,1)}</span><div><strong>{me.data?.first_name||'Espace restaurateur'}</strong><small>La maison KomandGo</small></div></div><nav className="resto-nav" aria-label="Navigation restaurateur">{nav.map(({href,label,Icon})=><Link key={href} href={href} className={path===href?'is-active':''} onClick={()=>setOpen(false)}><Icon/><span>{label}</span></Link>)}</nav><div className="resto-sidebar__bottom"><Link href="/profile"><UserRound/> Mon profil</Link><span className="resto-live"><i/> Données actualisées automatiquement</span></div></aside><div className="resto-main"><header className="resto-topbar"><button className="icon-button resto-menu" onClick={()=>setOpen(true)} aria-label="Ouvrir le menu"><Menu/></button><div><p className="kicker">Espace restaurateur</p><h1>{view==='dashboard'?'Réception des commandes':view==='history'?'Historique des commandes':'Vos statistiques'}</h1></div><button className="icon-button" aria-label="Notifications"><Bell/></button></header>{view==='dashboard'?<Reception orders={orders}/>:view==='history'?<History orders={orders}/>:<Stats stats={stats}/>}</div></div>}
function Reception({orders}:{orders:typeof demo}){return <section className="resto-content"><div className="resto-heading"><p>Suivez chaque commande dès son arrivée.</p><span className="resto-refresh"><RefreshCw/> Actualisation automatique · 15 s</span></div><div className="resto-kpis"><Kpi label="À traiter" value="02" tone="amber"/><Kpi label="En préparation" value="01"/><Kpi label="Prêtes" value="01" tone="soft"/></div><div className="order-stack">{orders.map(o=><OrderCard key={o.id} order={o}/>)}</div></section>}
function History({orders}:{orders:typeof demo}){return <section className="resto-content"><div className="resto-heading"><p>Retrouvez le détail des commandes et les coordonnées utiles en cas de problème.</p><button className="button button--secondary">Exporter la période</button></div><div className="history-filters"><button className="filter is-active">Toutes <b>426</b></button><button className="filter">Terminées <b>398</b></button><button className="filter">Abandonnées <b>28</b></button></div><div className="order-stack">{orders.concat(orders).map((o,i)=><OrderCard key={`${o.id}-${i}`} detailed order={{...o,status:i%4===0?'cancelled':'completed'}}/>)}</div></section>}
function Stats({stats}:{stats:{orders_today:number;orders_month:number;completed:number;abandoned:number;top_products:{name:string;quantity:number}[]}}){const rate=Math.round(stats.completed/(stats.completed+stats.abandoned)*100);return <section className="resto-content"><div className="stats-toolbar"><p>Une vue claire de l’activité de votre restaurant.</p><select aria-label="Période"><option>30 derniers jours</option><option>Cette semaine</option></select></div><div className="stats-grid"><Kpi label="Commandes aujourd’hui" value={String(stats.orders_today)} tone="amber"/><Kpi label="Commandes ce mois" value={String(stats.orders_month)}/><Kpi label="Taux de réussite" value={`${rate}%`} tone="soft"/></div><div className="stats-columns"><div className="panel"><div className="panel-heading"><div><h2>Commandes reçues</h2><p>Évolution sur les 7 derniers jours</p></div><span className="trend">+12,4% <TrendingUp/></span></div><div className="bars">{[42,58,49,74,65,92,78].map((h,i)=><div className="bar-wrap" key={i}><span className="bar" style={{height:`${h}%`}}/><small>{['Lun','Mar','Mer','Jeu','Ven','Sam','Dim'][i]}</small></div>)}</div></div><div className="panel"><div className="panel-heading"><div><h2>Produits populaires</h2><p>Les plus commandés</p></div><PackageCheck/></div><ol className="top-products">{stats.top_products.map((p,i)=><li key={p.name}><span>{i+1}</span><strong>{p.name}</strong><b>{p.quantity} ventes</b></li>)}</ol></div></div><div className="panel status-panel"><div className="panel-heading"><div><h2>Statut des commandes</h2><p>Sur la période sélectionnée</p></div></div><div className="progress-row"><div><span>Terminées</span><b>{stats.completed}</b></div><div className="progress"><i style={{width:`${rate}%`}}/></div></div><div className="progress-row"><div><span>Abandonnées</span><b>{stats.abandoned}</b></div><div className="progress progress--danger"><i style={{width:`${100-rate}%`}}/></div></div></div></section>}
function Kpi({label,value,tone}:{label:string;value:string;tone?:string}){return <div className={`resto-kpi ${tone?`resto-kpi--${tone}`:''}`}><span>{label}</span><strong>{value}</strong></div>}
function OrderCard({order,detailed=false}:{order:typeof demo[number];detailed?:boolean}){const kind=order.status==='cancelled'?'closed':order.status==='completed'?'open':'order';return <article className={`resto-order ${detailed?'resto-order--detailed':''}`}><div className="resto-order__main"><div className="resto-order__top"><span className={`status status--${kind}`}>{labels[order.status]}</span><span className="order-id">#{order.id} · {order.time}</span></div><h2>{order.customer}</h2><p>{order.items}</p><span className="order-address">{order.address}</span></div><div className="resto-order__customer"><span>Coordonnées client</span><b>{order.customer}</b><small>{detailed?'06 12 34 56 78 · client@exemple.fr':'Livraison à domicile'}</small></div><strong className="resto-order__total">{money(order.total)}<ChevronRight/></strong></article>}
import * as React from "react";


