# Generated by Django 5.2.16 on 2026-07-27 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=90)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ('position', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=110)),
                ('description', models.TextField(blank=True, max_length=800)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('allergens', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('delivery_enabled', models.BooleanField(default=True)),
                ('pickup_enabled', models.BooleanField(default=True)),
                ('onsite_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ('position', 'name'),
            },
        ),
        migrations.CreateModel(
            name='OptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('minimum', models.PositiveSmallIntegerField(default=0)),
                ('maximum', models.PositiveSmallIntegerField(default=1)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_groups', to='catalog.product')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.optiongroup')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['restaurant', 'is_active', 'position'], name='catalog_cat_restaur_3c12c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('restaurant', 'slug'), name='unique_category_slug_per_restaurant'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('restaurant', 'name'), name='unique_category_name_per_restaurant'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active', 'is_available', 'position'], name='catalog_pro_categor_76b093_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('category', 'slug'), name='unique_product_slug_per_category'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='product_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='optiongroup',
            constraint=models.CheckConstraint(condition=models.Q(('maximum__gte', models.F('minimum'))), name='option_group_maximum_gte_minimum'),
        ),
        migrations.AddConstraint(
            model_name='optiongroup',
            constraint=models.UniqueConstraint(fields=('product', 'name'), name='unique_option_group_name_per_product'),
        ),
        migrations.AddConstraint(
            model_name='productoption',
            constraint=models.CheckConstraint(condition=models.Q(('price_delta__gte', 0)), name='product_option_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='productoption',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='unique_option_name_per_group'),
        ),
    ]
